---
app:
  browser:
    executable: "/usr/bin/chromium"
    headless: false
  worker:
    instances: 1
    sleepInterval: 1000
  output:
    - type: file
      folder: "./result/"
auth:
  - winAd:
    type: "WinAdAuth"
    userMail: "andreas.karner@magna.com"
pages:
  - name: "google"
    url: "https://google.com"
    interval: 1
    auth: "winAd"
