---
app:
  browser:
    executable: "/usr/bin/chromium"
    headless: false
  output:
    - type: "file"
      folder: "./result/"
    - type: "http"
      method: "PUT"
      url: "http://localhost:2711/some/query"
auth:
  - type: "WinAdAuth"
    name: "winUser"
    userMail: "andreas.karner@magna.com"
pages:
  - name: "google"
    url: "https://google.com"
    interval: 10000
    auth: "winUser"
