---
app:
  browser:
    executable: "/usr/bin/chromium"
    headless: true
  worker:
    instances: 1
    sleepInterval: 1000
  output:
    - type: "file"
      folder: "./result/"
    - type: "http"
      method: "PUT"
      url: "https://localhost:2711/some/endpoint/{filename}"
auth:
  - name: "WinADPowerBi"
    type: "WinAdAuth"
    impl: "msPowerBi"
    userMail: "andreas.karner@student.tugraz.at"
    userPwd: "notNeededForWindowsAd"
pages:
  - name: "google"
    url: "https://google.com"
    interval: 0.1
    #auth: "none"
  - name: "fischRehka"
    url: "https://fisch.rehka.dev"
    interval: 5
    #auth: "WinADPowerBi"
